apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: repomind

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  # secrets.yaml is commented out - create secrets manually using kubectl
  # See k8s/README.md for instructions
  # - secrets.yaml

commonLabels:
  app: repomind
  managed-by: kustomize

